<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>
  </PropertyGroup>
  <ItemGroup>

    <Compile Remove="Module1.cs" />
    <Compile Remove="My\MyApplication.cs" />
    <Compile Remove="My\MyComputer.cs" />
    <Compile Remove="My\MyProject.cs" />
    <Compile Remove="My\Resources\Resources.cs" />
    <Compile Remove="ValidKeyEventArgs.cs" />
  </ItemGroup>
 
</Project>
